### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by webwurst** [dailymuse/gosass#1]
Hi Yusuf!

I have created a Dockerfile for gosass. Is that of interest for you?
https://github.com/giantswarm/gosass

**Comment by ysimonson** [comment]
Yes! Please make a PR and I'm happy to accept.

**Comment by ysimonson** [comment]
Hi @webwurst , if you have the chance could you make a PR with the Dockerfile?

**Comment by webwurst** [comment]
Hi @ysimonson, sorry for the delay, would love to. It would be cool, if we could fetch a binary to integrate in the Docker image. Could you create a release here on GitHub?

**Comment by ysimonson** [comment]
Why not compile from source? Otherwise the Dockerfile would have to be updated for each release.
