### ISSUE TITLE
Could not stage for compilation: Could not find ref

### ISSUE THREAD

**Issue by ndrew** [dailymuse/gosass#10]
When I am watching directory via 

    gosass --sourcemap --load-path scss  -input scss/ -output css/ --watch

and I change the sass file — I get the following error

    Could not stage for compilation: Could not find ref `../_scss/foo.scss` (tried '{PATH_OMMITTED}/redesign/_scss/_foo.scss.scss' and '{PATH_OMMITTED}/_scss/foo.scss.css')

The import statement in scss is like

    @import '../_scss/foo.scss';

It's strange that first compilation works, but later — it fails.

**Comment by ysimonson** [comment]
It should be `@import '../_scss/foo`.

**Comment by ndrew** [comment]
I've added a pull request that fixes this issue — https://github.com/dailymuse/gosass/pull/11
