### ISSUE TITLE
Not able to install this.

### ISSUE THREAD

**Issue by techhysahil** [dailymuse/gosass#4]
I was looking for watch and directory compilation feature for sassc and search landed me to your repo. I was really happy when i found this repo. First of all thanks for adding these feature and sassc does provide these options. But i am not able to install this, please help me.

I am using Mac.

**Comment by ysimonson** [comment]
What steps did you run? What errors did you get?

**Comment by techhysahil** [comment]
Firstly i cloned repo.
Then i go into gosass repo and type make but getting error.
Here is snapshot:
![screen shot 2015-11-09 at 12 15 09 pm](https://cloud.githubusercontent.com/assets/7847056/11027476/a0a4b9e4-86db-11e5-9d95-944ae17397c7.png)

i think i am missing something in installation instruction. Please help me out.

**Comment by ysimonson** [comment]
It looks like you don't have a `$GOPATH` set in your `~/.bash_profile`. You should add something like this to your `~/.bash_profile`, depending on where your Go source packages are installed:

    export GOPATH=~/go

**Comment by techhysahil** [comment]
Thanks

**Comment by ysimonson** [comment]
No problem, hope that fixes it.
