### ISSUE TITLE
_<file name with underscore prefix>.scss failed with "gosass watch" command

### ISSUE THREAD

**Issue by QBui** [dailymuse/gosass#5]
First of all, I want to say "Thank you" for this wonderful library. I just download it today and it works great for me.

One minor issue that I encountered was "gosass -watch" command failed to process file with the underscore (_) prefix after any scss file changes. I want to report this issue and my workaround solution in case other people may run into this issue.

[Reproduce]
1. Download bootstrap sass project
2. Run gosass with "watch" argument to watch for file changes.
3. Make some changes on bootstrap.scss file
4. A error will throw for some  __<some random file name>.scss not found (Sorry, I could not copy & paste the error since I reported this issue on another machine)

After inspecting the code, it looks like the issue caused by "refPath := filepath.Join(filepath.Dir(ref), fmt.Sprintf("_%s.scss", filepath.Base(ref)))" (line 46 in compiler/dependencies.go)

[Work around]
I have a work around by replacing "__" with "_" as following code 
strings.Replace(fmt.Sprintf("_%s.scss", filepath.Base(ref), "__", "_", 1)

Sorry, I don't know Go code so well, so feel free to make a correction where you see fit.

Thanks,
-Quan

**Comment by QBui** [comment]
Hum. My sample code get changed by Github. Anyway, a work around is to replace 2 underscores characters with 1 for the first occurrence.

**Comment by ysimonson** [comment]
Underscore-prefixed files in sass are partials. When you `@import "foo/bar"`, it should import the partial from the file `foo/_bar.scss`.rw
