### ISSUE TITLE
Watcher chokes on inlined CSS imports

### ISSUE THREAD

**Issue by cisso** [dailymuse/gosass#7]
libsass supports inlined .css imports (see https://github.com/sass/libsass/pull/754). Gosass handles these fine as well.
When using the `-watch` argument though, gosass will initially compile without errors, but on changes will interpret the file as partial and attempt to load `_{filename}.scss`.

### Example

Given the following file structure:
- `sass/style.scss`
- `sass/fonts/font.css`

and the following content for `style.scss`:
```
@import "fonts/font";
```

then invoking `gosass -input=sass/ -output=. -watch` will yield:
```
[sass/style.scss] Compiled to style.css
```
But any change to `sass/style.css` will result in the following error:
```
[sass/style.scss] Could not stage for compilation: open /[...]/sass/fonts/_font.scss: no such file or directory
```

**Comment by ysimonson** [comment]
Cool, didn't know this was possible. Could you try it with the [feature/includable-css branch](https://github.com/dailymuse/gosass/tree/feature/includable-css)?

**Comment by cisso** [comment]
Thanks for your quick response and fix! I just tested `feature/includable-css`, and inlined .css files are now properly included on watcher updates.

One (very minor) issue that remains is that changes to inlined .css files aren't detected by the watcher. Personally I can happily live that, since inlining .css is an edge case anyway (in my opinion). I'll leave it to you to decide wether you want to keep the issue open or close it.

Again, thanks for writing and supporting gosass. :)

**Comment by ysimonson** [comment]
I think I fixed that - let me know if it works now!

**Comment by ysimonson** [comment]
Just noticed a typo in the tests which caused them to fail. Let me know if it works and I'll merge it into develop.

**Comment by cisso** [comment]
Hi, sorry for the late feedback.

I just ran some tests with your latest commit, and changes to inlined .css files below the watched directory are now properly detected. Thanks again for your quick response and fix!

**Comment by ysimonson** [comment]
Cool, will merge - thanks for testing!

**Comment by cisso** [comment]
When do you plan to merge develop / this fix into master?

**Comment by ysimonson** [comment]
It's on develop. Have been using it for our needs for the past few days to make sure everything is OK, and it appears to be. I'll go ahead and push to master.
